#!/bin/sh
#
#	@(#)embed.sh	1.1
#
# Turns a file into a C header so the asset ends up inside the binary:
#
#	sh tools/embed.sh data/wall.tga > wall.h
#	...
#	#include "wall.h"
#	tga_Decode(pixels, cap, wall_tga, wall_tga_len);
#
# The engine cannot tell an embedded array from a read() buffer, so this
# changes nothing except where the bytes came from.
#
# Uses xxd when it is there and od when it is not - xxd ships with vim, so
# it is missing on a surprising number of otherwise complete machines,
# while od is in POSIX and has been everywhere since 1979.
#
# WHEN TO DO THIS, AND WHEN NOT TO.  Embedding is right for the handful of
# things the game cannot run without: the font atlas, the loading screen,
# the crosshair, a fallback texture.  It is wrong for levels.  Every
# embedded byte is a byte of .rodata, a byte the linker has to place, and a
# recompile every time an artist saves the file.  Past a megabyte or two,
# put the assets in a pack file and mmap() it - the engine side of the call
# is identical, only your loader changes.

if [ $# -lt 1 ]; then
	echo "usage: sh tools/embed.sh <file> [more files...]" >&2
	exit 1
fi

emit_with_od() {
	file=$1
	name=$2
	size=$(wc -c < "$file" | tr -d ' ')

	echo "static unsigned char ${name}[] = {"
	od -An -tx1 -v "$file" | awk '
	{
		for (i = 1; i <= NF; i++) {
			printf "0x%s, ", $i
			n++
			if (n % 12 == 0)
				printf "\n"
		}
	}
	END { if (n % 12 != 0) printf "\n" }'
	echo "};"
	echo "static unsigned int ${name}_len = ${size};"
}

echo "/* generated by tools/embed.sh - do not edit */"
echo "#ifndef EMBED_H_SENTRY"
echo "#define EMBED_H_SENTRY"
echo

for file in "$@"; do
	if [ ! -f "$file" ]; then
		echo "embed.sh: no such file: $file" >&2
		exit 1
	fi

	directory=$(dirname "$file")
	base=$(basename "$file")
	name=$(printf '%s' "$base" | tr -c 'A-Za-z0-9' '_')

	if command -v xxd > /dev/null 2>&1; then
		# xxd names the array after the path it was handed, so cd
		# into the directory first and the name comes out as
		# wall_tga rather than data_wall_tga.
		( cd "$directory" && xxd -i "$base" ) |
			sed 's/^unsigned /static unsigned /'
	else
		emit_with_od "$file" "$name"
	fi
	echo
done

echo "#endif"
